step2_fluidRow <- fluidRow(
      style = "margin-left: 10px;",
      column(
        6, align = "left", h3("Step 2. Quality Control."),
        p("Please input the parameters for quality control and preprocessing."),
        numericInput("nFeature_RNA.limit", "nFeature_RNA.limit (default: 200):", value = 200),
        numericInput("percent.mt.limit", "percent.mt.limit (default: 20):", value = 20),
        numericInput("scale.factor", "scale factor (default: 10,000):", value = 10000),
        numericInput("nfeatures", "nfeatures (default: 3,000):", value = 3000),
        numericInput("ndims", "ndims (default: 50):", value = 50),
        textInput("vars.to.regress", "vars.to.regress (default: NULL):", value = 'NULL'),
        textInput("PCs", "PCs (default: 1:35):", value = "1:35"),
        numericInput("resolution", "resolution (default: 0.4):", value = 0.4),
        numericInput("n.neighbors", "n.neighbors (default: 50):", value = 50),
        numericInput("doublet.percentage", "doublet percentage (default: 0.04):", value = 0.04),
        textInput("doublerFinderwraper.PCs", "doubletFinder Wrapper PCs (default: 1:20):", value = "1:20"),
        numericInput("doublerFinderwraper.pN", "doubletFinder Wrapper pN (default: 0.25):", value = 0.25),
        numericInput("doublerFinderwraper.pK", "doubletFinder Wrapper pK (default: 0.1):", value = 0.1),
        selectInput("Step2_Quality_Control.RemoveBatches", "Step2_Quality_Control.RemoveBatches:", choices = c("FALSE" = FALSE, "TRUE" = TRUE)),
        selectInput("Step2_Quality_Control.RemoveDoublets", "Step2_Quality_Control.RemoveDoublets:", choices = c("FALSE" = FALSE, "TRUE" = TRUE)),
        actionButton("RunStep2", "Run Step2"),
        div(class = "spacer"), 
        uiOutput("runningStep2"),
        div(class = "spacer"),  
        uiOutput("step2_completed")),
      column(
            6, align = "left",
            h3("Browse files in Step 2. Quality Control:"),
            uiOutput("Step2.file_list"))
    )